bump aap core, aap-juce and helio (up to some old revision).
It seems I was upgrading helio like half a year ago.

It still fails to launch at run time due to:

>     java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN3aap17PluginHostManager16isPluginUpToDateENSt6__ndk112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEx" referenced by "/data/app/~~TrxhJY52JGHdc8-VdXxPow==/fm.helio-ORkLyyTxFHazpU9MRdgzpw==/base.apk!/lib/x86/libjuce_jni.so"...